export const ubicaciones = {
  Aguascalientes: [
    "Aguascalientes",
    "Jesús María",
    "Calvillo",
    "Rincón de Romos",
    "Pabellón de Arteaga",
  ],
  "Baja California": [
    "Tijuana",
    "Mexicali",
    "Ensenada",
    "Tecate",
    "Rosarito",
    "San Quintín",
  ],
  "Baja California Sur": [
    "La Paz",
    "Cabo San Lucas",
    "San José del Cabo",
    "Loreto",
    "Constitución",
  ],
  Campeche: [
    "Campeche",
    "Ciudad del Carmen",
    "Champotón",
    "Escárcega",
    "Kalkiní",
  ],
  Chiapas: [
    "Tuxtla Gutiérrez",
    "San Cristóbal de las Casas",
    "Tapachula",
    "Comitán",
    "Palenque",
    "Chiapa de Corzo",
  ],
  Chihuahua: [
    "Chihuahua",
    "Ciudad Juárez",
    "Delicias",
    "Cuauhtémoc",
    "Parral",
    "Nuevo Casas Grandes",
  ],
  "Ciudad de México": [
    "Álvaro Obregón",
    "Benito Juárez",
    "Coyoacán",
    "Cuauhtémoc",
    "Iztapalapa",
    "Miguel Hidalgo",
    "Tlalpan",
    "Venustiano Carranza",
    "Gustavo A. Madero",
  ],
  Coahuila: [
    "Saltillo",
    "Torreón",
    "Monclova",
    "Piedras Negras",
    "Acuña",
    "Matamoros",
    "Parras",
  ],
  Colima: ["Colima", "Manzanillo", "Villa de Álvarez", "Tecomán", "Armería"],
  Durango: [
    "Durango",
    "Gómez Palacio",
    "Lerdo",
    "Santiago Papasquiaro",
    "Cuencamé",
  ],
  "Estado de México": [
    "Toluca",
    "Ecatepec",
    "Naucalpan",
    "Tlalnepantla",
    "Huixquilucan",
    "Metepec",
    "Nezahualcóyotl",
    "Chimalhuacán",
    "Cuautitlán Izcalli",
  ],
  Guanajuato: [
    "León",
    "Irapuato",
    "Celaya",
    "Salamanca",
    "Guanajuato",
    "San Miguel de Allende",
    "Silao",
    "Valle de Santiago",
  ],
  Guerrero: [
    "Acapulco",
    "Chilpancingo",
    "Zihuatanejo",
    "Iguala",
    "Taxco",
    "Tlapa de Comonfort",
  ],
  Hidalgo: [
    "Pachuca de Soto",
    "Tula de Allende",
    "Tulancingo",
    "Mineral de la Reforma",
    "Ixmiquilpan",
    "Huejutla de Reyes",
  ],
  Jalisco: [
    "Guadalajara",
    "Zapopan",
    "Tlaquepaque",
    "Tonalá",
    "Puerto Vallarta",
    "Tepatitlán",
    "Lagos de Moreno",
    "Ajijic",
  ],
  Michoacán: [
    "Morelia",
    "Uruapan",
    "Zamora",
    "Lázaro Cárdenas",
    "Pátzcuaro",
    "Zitácuaro",
    "Apatzingán",
  ],
  Morelos: [
    "Cuernavaca",
    "Jiutepec",
    "Cuautla",
    "Temixco",
    "Yautepec",
    "Emiliano Zapata",
  ],
  Nayarit: [
    "Acaponeta",
    "Ahuacatlán",
    "Amatlán de Cañas",
    "Bahía de Banderas",
    "Compostela",
    "Del Nayar",
    "Huajicori",
    "Ixtlán del Río",
    "Jala",
    "La Yesca",
    "Rosamorada",
    "Ruiz",
    "San Blas",
    "San Pedro Lagunillas",
    "Santa María del Oro",
    "Santiago Ixcuintla",
    "Tecuala",
    "Tepic",
    "Tuxpan",
    "Xalisco",
  ],
  "Nuevo León": [
    "Monterrey",
    "San Pedro Garza García",
    "San Nicolás de los Garza",
    "Guadalupe",
    "Apodaca",
    "Santa Catarina",
    "Escobedo",
    "Santiago",
  ],
  Oaxaca: [
    "Oaxaca de Juárez",
    "Salina Cruz",
    "Juchitán de Zaragoza",
    "Santa Cruz Huatulco",
    "Puerto Escondido",
    "San Juan Bautista Tuxtepec",
  ],
  Puebla: [
    "Puebla",
    "Tehuacán",
    "San Andrés Cholula",
    "San Pedro Cholula",
    "Atlixco",
    "San Martín Texmelucan",
    "Huauchinango",
  ],
  Querétaro: [
    "Santiago de Querétaro",
    "San Juan del Río",
    "Corregidora",
    "El Marqués",
    "Tequisquiapan",
    "Cadereyta de Montes",
  ],
  "Quintana Roo": [
    "Cancún",
    "Playa del Carmen",
    "Chetumal",
    "Cozumel",
    "Tulum",
    "Isla Mujeres",
    "Puerto Morelos",
  ],
  "San Luis Potosí": [
    "San Luis Potosí",
    "Ciudad Valles",
    "Matehuala",
    "Soledad de Graciano Sánchez",
    "Río Verde",
    "Tamazunchale",
  ],
  Sinaloa: [
    "Culiacán",
    "Mazatlán",
    "Los Mochis",
    "Guasave",
    "Guamúchil",
    "Navolato",
  ],
  Sonora: [
    "Hermosillo",
    "Ciudad Obregón",
    "Nogales",
    "Guaymas",
    "Navojoa",
    "San Luis Río Colorado",
    "Puerto Peñasco",
  ],
  Tabasco: [
    "Villahermosa",
    "Cárdenas",
    "Comalcalco",
    "Paraíso",
    "Huimanguillo",
    "Macuspana",
  ],
  Tamaulipas: [
    "Reynosa",
    "Matamoros",
    "Nuevo Laredo",
    "Tampico",
    "Ciudad Victoria",
    "Ciudad Madero",
    "Altamira",
  ],
  Tlaxcala: [
    "Tlaxcala",
    "Apizaco",
    "Huamantla",
    "Chiautempan",
    "San Pablo del Monte",
  ],
  Veracruz: [
    "Veracruz",
    "Xalapa",
    "Coatzacoalcos",
    "Boca del Río",
    "Orizaba",
    "Córdoba",
    "Poza Rica",
    "Tuxpan",
  ],
  Yucatán: ["Mérida", "Progreso", "Valladolid", "Tizimín", "Kanasín", "Motul"],
  Zacatecas: [
    "Zacatecas",
    "Fresnillo",
    "Guadalupe",
    "Jerez",
    "Sombrerete",
    "Río Grande",
  ],
} as const;

export type Estado = keyof typeof ubicaciones;
